
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- bash: |
    npm ci
    npm -v
    node -v
  displayName: 'Install dependencies'

- bash: |
    npx ng test --run --coverage
  displayName: 'Run Tests'

- bash: |
    npx ng build --configuration production
  displayName: 'Build Angular'
