
trigger:
- master   

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20.x'

- bash: |
    npm ci
    echo "Node:" && node -v
    echo "NPM:" && npm -v
    echo "Angular CLI:"
    npm exec -- ng version
  displayName: 'Install dependencies + Angular CLI check'

- bash: |
    npm exec -- ng test \
      --watch=false \
      --code-coverage \
      --browsers=ChromeHeadless
  displayName: 'Run Unit Tests (Angular - Chrome Headless)'
  
- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/**/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
    failIfCoverageEmpty: true
  displayName: 'Publish Coverage Report'

- bash: |
    npm exec -- ng build --configuration production
  displayName: 'Build Angular (production)'

